modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/LIUKRAST/Deployer/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://liukrast.net/mods/${mod_id}"
logoFile="${mod_id}"
credits="Mod credits here do not support multiline"
authors="${mod_authors}"
description='''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"
# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"
