modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/LIUKRAST/Deployer/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://liukrast.net/"
logoFile="${mod_id}.png"
credits="Credits to SWZO and Propants for the main idea"
authors="${mod_authors}"
description='''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="compat_manager"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="repackaged"
    type="optional"
    versionRange="[0.0.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="create_factory_logistics"
    type="incompatible"
    reason="Create Factory logistics is not supported and marked as incompatible with deployer. Learn more at https://github.com/LIUKRAST/Deployer/blob/master/fl.md"